version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5

    commit-message:
      prefix: 'chore'
      include: 'scope' 

    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - '*'
      version-updates:
        applies-to: version-updates
        patterns:
          - '*'

    labels:
      - 'dependencies'

    reviewers:
      - 'gruble'
      - 'amish1188'
      - 'NVEJoel'
      - 'tomapedersen'
