/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NveButton {
        "disabled": string;
        "label": string;
        "leadingIcon": string;
        "loading": boolean;
        "showLabel": boolean;
        "size": "large" | "medium" | "small" | "x-small";
        "trailingIcon": string;
        "type": "primary" | "secondary" | "outlined" | "ghost";
    }
}
declare global {
    interface HTMLNveButtonElement extends Components.NveButton, HTMLStencilElement {
    }
    var HTMLNveButtonElement: {
        prototype: HTMLNveButtonElement;
        new (): HTMLNveButtonElement;
    };
    interface HTMLElementTagNameMap {
        "nve-button": HTMLNveButtonElement;
    }
}
declare namespace LocalJSX {
    interface NveButton {
        "disabled"?: string;
        "label"?: string;
        "leadingIcon"?: string;
        "loading"?: boolean;
        "showLabel"?: boolean;
        "size"?: "large" | "medium" | "small" | "x-small";
        "trailingIcon"?: string;
        "type"?: "primary" | "secondary" | "outlined" | "ghost";
    }
    interface IntrinsicElements {
        "nve-button": NveButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nve-button": LocalJSX.NveButton & JSXBase.HTMLAttributes<HTMLNveButtonElement>;
        }
    }
}
