/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NveButton {
        "disabled": boolean;
        "label": string;
        "leadingIcon"?: string;
        "loading": boolean;
        "showLabel": boolean;
        "size": 'large' | 'medium' | 'small' | 'x-small';
        "trailingIcon"?: string;
        "type": 'primary' | 'secondary' | 'outlined' | 'ghost';
        "variant": 'nve' | 'varsom';
    }
    interface NveCheckbox {
        "checked": boolean;
        "indeterminate": boolean;
        "label": string;
    }
}
declare global {
    interface HTMLNveButtonElement extends Components.NveButton, HTMLStencilElement {
    }
    var HTMLNveButtonElement: {
        prototype: HTMLNveButtonElement;
        new (): HTMLNveButtonElement;
    };
    interface HTMLNveCheckboxElement extends Components.NveCheckbox, HTMLStencilElement {
    }
    var HTMLNveCheckboxElement: {
        prototype: HTMLNveCheckboxElement;
        new (): HTMLNveCheckboxElement;
    };
    interface HTMLElementTagNameMap {
        "nve-button": HTMLNveButtonElement;
        "nve-checkbox": HTMLNveCheckboxElement;
    }
}
declare namespace LocalJSX {
    interface NveButton {
        "disabled"?: boolean;
        "label"?: string;
        "leadingIcon"?: string;
        "loading"?: boolean;
        "showLabel"?: boolean;
        "size"?: 'large' | 'medium' | 'small' | 'x-small';
        "trailingIcon"?: string;
        "type"?: 'primary' | 'secondary' | 'outlined' | 'ghost';
        "variant"?: 'nve' | 'varsom';
    }
    interface NveCheckbox {
        "checked"?: boolean;
        "indeterminate"?: boolean;
        "label"?: string;
    }
    interface IntrinsicElements {
        "nve-button": NveButton;
        "nve-checkbox": NveCheckbox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nve-button": LocalJSX.NveButton & JSXBase.HTMLAttributes<HTMLNveButtonElement>;
            "nve-checkbox": LocalJSX.NveCheckbox & JSXBase.HTMLAttributes<HTMLNveCheckboxElement>;
        }
    }
}
