/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NveButton {
        "caret": boolean;
        "circle": boolean;
        "disabled": string;
        "download": string | undefined;
        "form": string;
        "formAction": string;
        "formEnctype": 'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain';
        "formMethod": 'post' | 'get';
        "formNoValidate": boolean;
        "formTarget": '_self' | '_blank' | '_parent' | '_top';
        "href": string;
        "label": string;
        "leadingIcon": string;
        "loading": boolean;
        "name": string;
        "outline": boolean;
        "pill": boolean;
        "rel": string;
        "size": "large" | "medium" | "small" | "x-small";
        "target": '_blank' | '_parent' | '_self' | '_top';
        "trailingIcon": string;
        "type": "primary" | "secondary" | "outlined" | "ghost";
        "value": string;
        "variant": 'default' | 'primary' | 'success' | 'neutral' | 'warning' | 'danger' | 'text';
    }
}
declare global {
    interface HTMLNveButtonElement extends Components.NveButton, HTMLStencilElement {
    }
    var HTMLNveButtonElement: {
        prototype: HTMLNveButtonElement;
        new (): HTMLNveButtonElement;
    };
    interface HTMLElementTagNameMap {
        "nve-button": HTMLNveButtonElement;
    }
}
declare namespace LocalJSX {
    interface NveButton {
        "caret"?: boolean;
        "circle"?: boolean;
        "disabled"?: string;
        "download"?: string | undefined;
        "form"?: string;
        "formAction"?: string;
        "formEnctype"?: 'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain';
        "formMethod"?: 'post' | 'get';
        "formNoValidate"?: boolean;
        "formTarget"?: '_self' | '_blank' | '_parent' | '_top';
        "href"?: string;
        "label"?: string;
        "leadingIcon"?: string;
        "loading"?: boolean;
        "name"?: string;
        "outline"?: boolean;
        "pill"?: boolean;
        "rel"?: string;
        "size"?: "large" | "medium" | "small" | "x-small";
        "target"?: '_blank' | '_parent' | '_self' | '_top';
        "trailingIcon"?: string;
        "type"?: "primary" | "secondary" | "outlined" | "ghost";
        "value"?: string;
        "variant"?: 'default' | 'primary' | 'success' | 'neutral' | 'warning' | 'danger' | 'text';
    }
    interface IntrinsicElements {
        "nve-button": NveButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nve-button": LocalJSX.NveButton & JSXBase.HTMLAttributes<HTMLNveButtonElement>;
        }
    }
}
