name: Reusable Build and Deploy Workflow

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node.js version'
        required: true
        type: string
      app_location:
        description: 'Location of the application code'
        required: true
        type: string
      output_location:
        description: 'Build output location'
        required: true
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: ${{ inputs.app_location }}
          output_location: ${{ inputs.output_location }}
          app_build_command: 'npm run build'
