name: Publish package to npmjs and Generate Changelog

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build/**'
      - 'public/css/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file and Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      # Generate version number and changelog
      - name: Run standard-version
        run: |
          npm run release
          git config --global user.email "jobl@nve.no"
          git config --global user.name "Designsystem"
          git push --follow-tags

      # Build the package
      - name: Build package
        run: npm run build

      # Publish the package to npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
