# name: Publish package to npmjs

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'src/**'
#       - 'build/**'
#       - 'public/css/**'
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       # Setup .npmrc file to publish to npm
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '20.x'
#           registry-url: 'https://registry.npmjs.org'

#       - name: Build and Publish
#         run: |
#           npm i
#           npm run build
#           git config --global user.email "jobl@nve.no"
#           git config --global user.name "Designsystem"
#           npm version patch -m "Bump version to %s [skip ci]" --force
#           git push --follow-tags
#           npm run publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}

name: Publish package to npmjs and Generate Changelog

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build/**'
      - 'public/css/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Release with release-please
        uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: 'nve-designsystem'

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
