# TODO - Update the branch name to the main branch when testing is finished.
# name: Enforce Conventional PR Title

# on:
#   pull_request:
#     branches:
#       - main
#     types:
#       - opened
#       - edited
#       - synchronize

# jobs:
#   lint_pr_title:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: amannn/action-semantic-pull-request@v3.5.0
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           titleOnly: true

name: Enforce Conventional PR Title

on:
  pull_request:
    branches:
      - test-release
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          titleOnly: true
          types: |
            fix 
            feat
            docs
