# .github/workflows/pr-title-check.yml
name: Enforce Conventional PR Title

on:
  pull_request:
    branches:
      - test-release # This runs when a PR targets the `test-release` branch
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enforce Conventional PR Title
        uses: CondeNast/conventional-pull-request-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
