name: Build, Release, and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build/**'
      - 'public/css/**'
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Semantic Release
        id: semantic_release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git for version bump
        if: ${{ success() }}
        run: |
          git config --global user.email "jobl@nve.no"
          git config --global user.name "Designsystem"

      # - name: Publish new version to npm
      #   if: ${{ success() }}
      #   run: |
      #     npm run publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
