name: Build, Release, and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build/**'
      - 'public/css/**'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate bot app token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DESIGNSYSTEM_RELEASER_ID }}
          private-key: ${{ secrets.DESIGNSYSTEM_RELEASER_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Get bot user ID
        id: bot-user-id
        run: |
          echo "user-id=$(gh api "/users/${{ steps.generate_token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Log GIT_AUTHOR_EMAIL and GIT_COMMITTER_EMAIL
        run: |
          echo "GIT_AUTHOR_EMAIL=${{ steps.bot-user-id.outputs.user-id }}+${{ steps.generate_token.outputs.app-slug }}[bot]@users.noreply.github.com"
          echo "GIT_COMMITTER_EMAIL=${{ steps.bot-user-id.outputs.user-id }}+${{ steps.generate_token.outputs.app-slug }}[bot]@users.noreply.github.com"

      - name: Run Semantic Release
        id: semantic_release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GIT_AUTHOR_EMAIL: '${{ steps.bot-user-id.outputs.user-id }}+${{ steps.generate_token.outputs.app-slug }}[bot]@users.noreply.github.com'
          GIT_COMMITTER_EMAIL: '${{ steps.bot-user-id.outputs.user-id }}+${{ steps.generate_token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Configure Git for version bump
        if: ${{ success() }}
        run: |
          git config --global user.email "jobl@nve.no"
          git config --global user.name "Designsystem"

      - name: Publish new version to npm
        if: ${{ success() }}
        run: |
          npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
