name: Update Components Design Versions

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run update script
        run: |
          node updateDocs.js

      - name: Commit changes
        run: |
          git config --global user.email "jobl@nve.no"
          git config --global user.name "Designsystem"
          git add .
          git commit -m "Update Components design versions from Figma"
          git push
